/**
 * Created by ermak on 01.02.17.
 */

export const OPEN_POPUP_EDIT_DIALOG  = 'OPEN_POPUP_EDIT_DIALOG';
export const SAVE_POPUP_EDIT_DIALOG  = 'SAVE_POPUP_EDIT_DIALOG';
export const CLOSE_POPUP_EDIT_DIALOG = 'CLOSE_POPUP_EDIT_DIALOG';

export const OPEN_DIALOG_INFO = 'OPEN_DIALOG_INFO';
export const CLOSE_DIALOG_INFO = 'CLOSE_DIALOG_INFO';

export const OPEN_DIALOG_REFERENCE_POINT = 'OPEN_DIALOG_REFERENCE_POINT';
export const CLOSE_DIALOG_REFERENCE_POINT = 'CLOSE_DIALOG_REFERENCE_POINT';

export const OPEN_MAP_CREATE_MODAL = 'OPEN_MAP_CREATE_MODAL';
export const SAVE_MAP_CREATE_MODAL = 'SAVE_MAP_CREATE_MODAL';
export const CLOSE_MAP_CREATE_MODAL = 'CLOSE_MAP_CREATE_MODAL';

export const ACTIVATE_REFERENCE_POINT_MODE = 'TOGGLE_REFERENCE_POINT_MODE';
export const OPEN_REFERENCE_POINT_MODAL = 'OPEN_REFERENCE_POINT_MODAL';
export const SAVE_REFERENCE_POINT_MODAL = 'SAVE_REFERENCE_POINT_MODAL';
export const CLOSE_REFERENCE_POINT_MODAL = 'CLOSE_REFERENCE_POINT_MODAL';

export const REMOVE_MAP_EDIT_DIALOG = 'REMOVE_MAP_EDIT_DIALOG';
export const CHANGE_MAP_EDIT_DIALOG = 'CHANGE_MAP_EDIT_DIALOG';
export const CHANGE_BACKGROUND_MAP_CREATE_MODAL = 'CHANGE_BACKGROUND_MAP_CREATE_MODAL';

export const EDIT_ACTION ='EDIT_ACTION';
export const EDIT_ACTION_AREA ='EDIT_ACTION_AREA';
export const EDIT_ACTION_GRAPH ='EDIT_ACTION_GRAPH';
export const EDIT_ACTION_WALL ='EDIT_ACTION_WALL';
export const EDIT_ACTION_BOUNDS_BG ='EDIT_ACTION_BOUNDS_BG';
export const EDIT_ACTION_ANCHORS = 'EDIT_ACTION_ANCHORS';
export const EDIT_ACTION_LANDMARKS = 'EDIT_ACTION_LANDMARKS';

// export const EDIT_ACTION_ANCHORS_ADD = 'EDIT_ACTION_ANCHORS_ADD';
// export const EDIT_ACTION_ANCHORS_REMOVE = 'EDIT_ACTION_ANCHORS_REMOVE';
// export const EDIT_ACTION_ANCHORS_MANUAL = 'EDIT_ACTION_ANCHORS_MANUAL';
// export const EDIT_ACTION_SHOW_ANCHOR_EDIT_TOOLS = 'EDIT_ACTION_SHOW_ANCHOR_EDIT_TOOLS';

export const UPDATE_LIST_MAPS = 'UPDATE_LIST_MAPS';
export const SELECT_MAP = 'SELECT_MAP';

export const UPDATE_PANEL_COLOR_BACKGROUND = 'UPDATE_PANEL_COLOR_BACKGROUND';
export const UPDATE_PANEL_COLOR_FONT = 'UPDATE_PANEL_COLOR_FONT';
export const SHOW_PANEL = 'SHOW_PANEL';

export const SELECT_ELEMENT_STYLE = 'SELECT_ELEMENT_STYLE';
export const CHECKED_NOTIFICATIONS = 'CHECKED_NOTIFICATIONS';
export const SET_NEW_SETTING_VALUE_BY_KEY = 'SET_NEW_SETTING_VALUE_BY_KEY';

export const OPEN_MAP_EDIT = "OPEN_MAP_EDIT";

export const OPEN_MAP_EDIT_PROPS_MODAL = 'OPEN_MAP_EDIT_PROPS_MODAL';
export const SAVE_MAP_EDIT_PROPS_MODAL = 'SAVE_MAP_EDIT_PROPS_MODAL';
export const CLOSE_MAP_EDIT_PROPS_MODAL = 'CLOSE_MAP_EDIT_PROPS_MODAL';
export const CHANGE_BACKGROUND_MAP_EDIT_PROPS_MODAL = "CHANGE_BACKGROUND_MAP_EDIT_PROPS_MODAL";
export const DELETE_MAP_EDIT_PROPS_MODAL = "DELETE_MAP_EDIT_PROPS_MODAL";

export const MAP_HOMEWARD = "MAP_HOMEWARD";
export const OPEN_MAP_ROOT = "OPEN_MAP_ROOT";

export const CLOSE_MAP_ROOT = "CLOSE_MAP_ROOT";

export const MAP_RTMODE = "MAP_RTMODE";
export const MAP_RTCONSIST = "MAP_RTCONSIST";

// Editing data ============>
export const EDITING_DATA__SELECT = 'EDITING_DATA__SELECT';
export const EDITING_DATA__EDIT = 'EDITING_DATA__EDIT';
export const EDITING_DATA__CREATE = 'EDITING_DATA__CREATE';
export const EDITING_DATA__DELETE = 'EDITING_DATA__DELETE';
export const EDITING_DATA__SAVE = 'EDITING_DATA__SAVE';
export const EDITING_DATA__CANCEL = 'EDITING_DATA__CANCEL';
// <============ Editing data

export const CLOSE_MAP_DELETE_MODAL = 'CLOSE_MAP_DELETE_MODAL';

export const TOGGLE_MEASURE_DISTANCE = "TOGGLE_MEASURE_DISTANCE";
export const DEACTIVATE_MEASURE_DISTANCE = "DEACTIVATE_MEASURE_DISTANCE";
export const DEACTIVATE_REFERENCE_MODE = "DEACTIVATE_REFERENCE_MODE";
